services:
  rustfs_perms:
    image: alpine
    user: root
    restart: "no"
    volumes:
      - /mnt/backup/rustfs:/fix_path
    command: chown -R 10001:10001 /fix_path

  rustfs:
    image: rustfs/rustfs:latest
    depends_on:
      rustfs_perms:
        condition: service_completed_successfully

    ports:
      - "9000:9000"
      - "9001:9001"

    environment:
      RUSTFS_ACCESS_KEY: ${RUSTFS_ACCESS_KEY}
      RUSTFS_SECRET_KEY: ${RUSTFS_SECRET_KEY}

    volumes:
      - /mnt/backup/rustfs:/data

    restart: unless-stopped
